version: '3.3'
volumes:
  data:
services:
  swapi-db:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=swapi_db