spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/swapi_db
    username: root
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      org:
#        hibernate:
#          flushMode: COMMIT

blocking-app-url: "http://127.0.0.1:8080"
swapi-url: "https://swapi.co/api/"

#TODO revisar E REMOVER